### ISSUE TITLE
Tipo de base de datos

### ISSUE THREAD

**Issue by UO265336** [Arquisoft/radarin_es6b#20]
¿Que tipo de base de datos vamos a usar para la el almacenamiento de localizaciones y otros datos?

**Comment by uo269948** [comment]
Podríamos usar MongoDB para la persistencia de las localizaciones de los usuarios. Para el resto de la información podríamos guardarla en los pods.
Documentación: https://www.mongodb.com/es/what-is-mongodb

**Comment by FernandoGiganto** [comment]
Estoy de acuerdo con @uo269948 . Además, en el proyecto inicial que se nos entregó ya utiliza esta base de datos por lo que me parece buena idea mantenerla.

**Comment by UO265336** [comment]
Estoy de acuerdo en usar MongoDB como una base de datos relacional

**Comment by uo271246** [comment]
Yo también estoy de acuerdo.

**Comment by MonicaVillanuevaPolledo** [comment]
Sí yo también opino igual en cuanto a usar MongoDB
