### ISSUE TITLE
Revisión documentación

### ISSUE THREAD

**Issue by cidinene** [Arquisoft/radarin_es6b#21]
Principales problemas :
 - La arquitectura, tal como está diseñada, centraliza toda la seguridad e información de los usuarios de manera centralizada, diseñando un único sistema que comunica con todos los Pods.  
 - Falta el componente software de aplicación móvil. 

La modificación de los apartados anteriores llevará el cambio de los demás apartados, con lo que se espera a que está cambiado para volver a revisar

**Comment by uo269948** [comment]
Puntos 2, 4, 8 y 11 modificados añadiendo la parte de la aplicación móvil. Listos para revisión.
Hecho con @FernandoGiganto
