### ISSUE TITLE
Prototipo de mapa de navegación de la aplicación web

### ISSUE THREAD

**Issue by UO265336** [Arquisoft/radarin_es6b#22]
![MapaNavegacion (1)](https://user-images.githubusercontent.com/57078190/110922296-cc50bc00-831f-11eb-8d2a-3c1a3c5439ac.png)

**Comment by MonicaVillanuevaPolledo** [comment]
Sobre las pantallas de login y signup @uo271246 y yo hemos pensado que en lugar de crear el formulario como en la imagen podemos enlazar directamente a la pagina de inrupt

**Comment by UO265336** [comment]
Cambio en el prototipo de la interfaz gráfica
![web (1)](https://user-images.githubusercontent.com/57078190/112612654-76037300-8e1f-11eb-88ce-d956149725f2.png)

**Comment by UO265336** [comment]
Prototipo base de la aplicación movil
![movil](https://user-images.githubusercontent.com/57078190/112612831-ae0ab600-8e1f-11eb-9e13-66ba6a567380.png)
