### ISSUE TITLE
Error al pasar los test del build-test-webapp

### ISSUE THREAD

**Issue by FernandoGiganto** [Arquisoft/radarin_es6b#23]
En local funcina bien y no da ni errores ni warnings, pero al subirlo y pasar los test dan el siguiente error:
"npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing."

Hacemos el npm install pero sigue sin fucionar.

**Comment by UO265336** [comment]
Solucionado el problema de dependencias de React. El problema era el lugar donde se almacenaban las dependencias. Se almacenaban el el package del proyecto general y no en la parte de la aplicación web.
