### ISSUE TITLE
Login inrupt app movil

### ISSUE THREAD

**Issue by FernandoGiganto** [Arquisoft/radarin_es6b#26]
Problemas al intentar hacer login con inrupt desde la app móvil. Hay que buscar más ejemplos de esta función.

**Comment by FernandoGiganto** [comment]
https://forum.solidproject.org/t/login-in-solid-pods-with-react-native/4116/8 -> Se dice que el login no lo tienen testeado en react native por lo que no pueden darnos solución. Hay que seguir buscando

**Comment by UO270656** [comment]
De momento mi idea es poner un login normal utilizando Firebase, una plataforma de Google. La idea es que el registro/login de la aplicación móvil y el de solid estén asociados, pero sin ser el mismo. 
Al estar asociados podremos podremos autentificar la identidad del usuario en el móvil sin que tenga que utilizar inrupt.
El problema de esta solución será que las peticiones que se realicen desde el móvil, como seria ver la lista de los amigos, se complicarán.

**Comment by FernandoGiganto** [comment]
Con el cambio de estrategia ya no va a hacer falta hacer este login.

**Comment by FernandoGiganto** [comment]
![mapa](https://user-images.githubusercontent.com/60341554/114785098-776bef80-9d7c-11eb-8b24-9f334a76f445.jpeg)
![noti](https://user-images.githubusercontent.com/60341554/114785102-78048600-9d7c-11eb-8d49-85fb816bfc92.jpeg)
