### ISSUE TITLE
Eliminación de la aplicación movil

### ISSUE THREAD

**Issue by UO265336** [Arquisoft/radarin_es6b#34]
Se ha decidido dejar de desarrollar la aplicación web por problemas con el login de Solid con React native y por falta de documentación. En su lugar se va a dar acceso a la página web a través de dispositivos móviles.

**Comment by FernandoGiganto** [comment]
#26 Para más información del problema

**Comment by FernandoGiganto** [comment]
Añadido en el apartado 9 de la documentación una explicación de los problemas encontrados a la hora de desarrollar la app móvil.
