### ISSUE TITLE
Monitorizar servidor MongoDB

### ISSUE THREAD

**Issue by uo271246** [Arquisoft/radarin_es6b#51]

**Comment by uo271246** [comment]
@UO270656 y yo encontramos la siguiente página con un tutorial:
https://devconnected.com/mongodb-monitoring-with-grafana-prometheus/

**Comment by UO270656** [comment]
El problema de ese tutorial y de otros que encontré, es que el "MongoDB exporter" solo te dan la opción de instalarlo en linux o en DarwinOS.

**Comment by UO270656** [comment]
@uo271246 Hemos conseguido enviar alertas por Discord con grafana.

**Comment by uo271246** [comment]
Finalmente no vamos a monitorizar MongoDB debido a su complejidad. Encontramos este plugin pero para utilizarlo hay que pedir permiso, sobre el cual consultamos pero no obtuvimos respuesta. Adjunto imágenes y el link de la página de dicho plugin.

https://grafana.com/grafana/plugins/grafana-mongodb-datasource/

![Plugin](https://user-images.githubusercontent.com/78324143/116690139-4107b480-a9b9-11eb-8cb1-a4c2c611f53a.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/78324143/116690495-bd9a9300-a9b9-11eb-9ee2-15050b69acca.png)
