### ISSUE TITLE
Problema tests BDD

### ISSUE THREAD

**Issue by uo269948** [Arquisoft/radarin_es6b#52]
Han surgido una serie de problemas realizando estos tests:
- No podemos hacer uso del global.page.goto('http://localhost:3000/...') ya que todo se ejecuta en el 'http://localhost:3000'. En un principio si que teníamos cada vista con su url pero tuvimos que modificarlo debido a que no funcionaba al subirlo a heroku. 
- Al iniciar la aplicación, debemos registrarnos con un botón de log in, que es un componente de react. No deja ponerle un id para hacer referencia a él para posteriormente hacerle poder hacerle click y tampoco deja acceder por el className.

Aunque volvamos a la versión anterior de las urls para cada vista, ¿cómo accedemos al botón de registrarse que se necesita al inicio de cada test?

**Comment by MonicaVillanuevaPolledo** [comment]
He conseguido acceder al botón de login mediante esta línea de código:
 await expect(page).toClick("button", { className: "logButton" });

Siendo _page_ una pagina del navegador que se crea para hacer las pruebas y _className_ el nombre asignado al boton

**Comment by uo269948** [comment]
Ya hemos conseguido solucionar los problemas sin usar las urls y ya podemos hacer log in y log out
