### ISSUE TITLE
Envio de notificaciones en dispositivo movil

### ISSUE THREAD

**Issue by FernandoGiganto** [Arquisoft/radarin_es6b#56]
Con la primera solución del envió de notificaciones, funcionaba bien en web pero no fui capaz a que funcionase en Android. En principio, según ponía la documentación, si debería funcionar. La propia clase tiene una función que detecta desde que buscador se esta intentando mandar la notificación y si este no es compatible manda una alerta. Esto funciona correctamente ya que hice la prueba en IOS, que no es compatible y manda el mensaje, pero en Android no por lo que no se si  es algo de la configuración del móvil o un fallo en la función( cosa que no debería ser).

Buscando más alternativas hice varias pruebas con firebase cloud messaging, con la que no consigo obtener una solución funcional.

algunos LINKS:
1)Opción --->push.js: https://www.npmjs.com/package/react-push-notification 
2)Opción --->firebase: https://firebase.google.com/docs/cloud-messaging/js/client?hl=es-419

**Comment by UO270656** [comment]
He visto el código que tenías para las notificaciones con push.js. He intentado que funcionase para Android, pero tampoco lo conseguí. He intentado enviar las notificaciones con ayuda del constructor Notification, porque al principio pensaba que el problema estaba con el método Push.create, pero aún haciéndolo así no me funcionó.

También he comprobado que el navegador que uso en el móvil permite las notificaciones y que estas están habilitadas, así que ya no se me ocurre en donde puede estar el problema con este método.

Intentaré probar próximamente la segunda opción que dices, con Firebase.

**Comment by UO270656** [comment]
Como alternativa a la opción de firebase, he hecho otro tipo de notificaciones. Las notificaciones por defecto son las de la api html5, siempre y cuando el dispositivo que acceda a la página sea un móvil. Si es un móvil, se detecta y en vez de enviar estas notificaciones (que ya se comprobó que no funcionan) se envía unas notificaciones en pantalla. No es la mejor solución porque si el navegador está en segundo plano, que es como estará la mayoría del tiempo, no nos llegarán estas notificaciones a la barra de notificaciones de nuestro dispositivo, pero servirían como ultima alternativa, para no dejar a los dispositivos móviles sin ningún tipo de notificación.

**Comment by FernandoGiganto** [comment]
He conseguido que me funcione un proyecto auxiliar que he creado con el firebase cloud messaging, el problema otra vez es que me sale un error diciendo que la API no está soportada, lo cual no tiene sentido porque como se puede ver en  este enlace: https://caniuse.com/push-api , si que lo está.
Este proyecto se puede ver en el siguiente repositorio: https://github.com/FernandoGiganto/prueba-notificaciones-firebase

**Comment by FernandoGiganto** [comment]
Finalmente se ha aptado por la solución de mensajes en pantalla
